### PR TITLE
PQSWMBT-4163 - new 'cops' asset, new 'pcu' device

### PR DESCRIPTION
**Pull request by jeffdegott**

### CODE REVIEW

**Review by stark-dev — APPROVED** [review]
I will take care of adding those new types to asset DTO and to convert them properly to string

**Review by stark-dev — APPROVED** [review]

**Comment by stark-dev** [comment]
FYI: new asset DTO has been updated to match those changes

**Comment by stark-dev** [comment]
> FYI: new asset DTO has been updated to match those changes

Reverted until final naming is approved

**Comment by jeffdegott** [comment]
@stark-dev new device subtype: 'pcu' as Parallel Control Unit

**Comment by stark-dev** [comment]
> @stark-dev new device subtype: 'pcu' as Parallel Control Unit
thanks, I will update the DTO ;)

**Pull request merged**
