### PR TITLE
Add a function to get the polling interval of the system

### PR DESCRIPTION
**Pull request by barraudl**
Signed-off-by: barraudl <lilianbarraud@eaton.com>

### CODE REVIEW

**Comment by jana-rapava** [comment]
@barraudl I'm sorry if it's not clear from the README, but functions depending on CZMQ/Malamute belong to fty-common-mlm, not fty-common

**Comment by geraldguillaume** [comment]
> @barraudl I'm sorry if it's not clear from the README, but functions depending on CZMQ/Malamute belong to fty-common-mlm, not fty-common

note @jana-rapava that fty-common-mlm library is also depending to cxxtools. As fty-common is widely used by fty-agents, it could make sense to allow fty-common to depend to CZMQ. What do you think ?

**Comment by jimklimov** [comment]
Better not complicate the dependency tree worse than we have it already; remember the impact on Travis rebuilds and the need to redefine and regenerate tens of project.xml's, if nothing else.

Also, we do have a common component dealing with ZMQ stack, so it really belongs there. The fty-common should be relevant for things that do not use ZMQ as well, and this segregation and reduction of unwarranted build and run-time (DLL) dependencies was one of the causes we split the many commons into different subjects and repos.

**Comment by jana-rapava** [comment]
@geraldguillaume : I do not think making fty-common depend on CZMQ is good idea. If we want to avoid adding unnecessary dependencies on cxxtools, I sugget splitting fty-common-mlm into functions which depend on CZMQ/Malamute and functions which depends on cxxtools . What do you think?

**Comment by geraldguillaume** [comment]
But ZMQ is aleady implictly referenced in this project.

A code block from CZMQ_PRELUDE_H was manually added here :
https://github.com/42ity/fty-common/blob/master/src/fty_common_classes.h#L40 

This is not a good practise to modify a 100% generated code.

**Comment by jana-rapava** [comment]
@geraldguillaume this is not added manually, it's generated by zproject - @jimklimov can confirm that :-)

**Comment by geraldguillaume** [comment]
@jana-rapava you are right, my zproject was not enough uptodate

**Comment by geraldguillaume** [comment]
@EldoreiJK what do you think ?

**Comment by jimklimov** [comment]
Well, czmq pulled by zproject inherently is sonething that can change, as now zproject is used for not purely MQ components management. Also being just mentioned in recipes should not add link/run-time dependencies (ELF cleaners might remove it if there, and no run-time overheads and incompatibilities tto care about if linked objects are not really used).

**Comment by aquette** [comment]
jumping into the discussion: @geraldguillaume  and @barraudl 
the added function relates to fty-nut only, not fty in general. So why not putting it as a public function in fty-nut? that would solve the point ;)

**Comment by aquette** [comment]
Update for later: since this is very NUT oriented, moving it to the now-existing fty-common-nut should be the solution.
@boricj: if you happen to have a few minutes to spare and inject there (changes actually limited to {include,src}/fty_common_base.{h,cc}
@barraudl: could you please remind me what was the use of this in the end?

Todo: implement a setter + REST

**Comment by boricj** [comment]
@aquette Looks good to me once moved to fty-common-nut (and adjusted to fit its API style).

**Comment by EldoreiJK** [comment]
I second the thought to move this to fty-common-nut. Anyway I don't see any good reason for making such fty-common-nut, as this might easily lead to have one common repo for each agent. The idea was to keep this simple. What I got from the changes is that this is intended to unify approach to data acquisition, hence it should go to some kind of fty-common-data-acquisition which would be responsible for whatever data model we intend to use. In the best future this would create an interface for obtaining data regardless of mlm/shm/whatever, so you just request data, and that's it for you. And this would in the end overshadow fty-common-mlm, as mlm would be just provider for fty-common-data-acquisition.

**Pull request closed without merging**
