### PR TITLE
[Do not merged yet]

### PR DESCRIPTION
**Pull request by MimiXav**

### CODE REVIEW

**Comment by aquette** [comment]
@MimiXav @geraldguillaume this PR is sitting here for 2 weeks, and seems incomplete / is outdated.
If still applicable, please amend, otherwise please close. thx

**Comment by aquette** [comment]
@MimiXav @geraldguillaume this PR is sitting here for 2 weeks, and seems incomplete / is outdated.
If still applicable, please amend, otherwise please close. thx

**Comment by geraldguillaume** [comment]
@MimiXav, could you please check the interrest of this PR after the reworking done on fty-common-XXX

**Comment by MimiXav** [comment]
That's no longer news

**Pull request closed without merging**
